"""Audit the real PIPE2 receipt against the v2 handoff descriptor.

This is a read-only, zero-API, zero-GPU audit.  It reports which descriptor
fields are actually present in the native runtime receipt and which are
missing.  It never infers judgment, action, or terminal outcome from adoption
or self-score fields.
"""

from __future__ import annotations

import argparse
from dataclasses import fields
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import platform
import subprocess
import sys
from typing import Any

from peerrolebench_pipe2_handoff_descriptor_v2 import (
    Pipe2HandoffDescriptor,
    SCHEMA,
)


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "experiments/logs/n03_pipe2_derived_root_runtime_qualification_20261003_v3/summary.json"
RUNNER_VERSION = "pipe2-v2-runtime-field-gap-audit-v1"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _walk(value: Any, prefix: str = "") -> set[str]:
    """Return dotted paths for keys in the first real receipt case."""
    paths: set[str] = set()
    if isinstance(value, dict):
        for key, child in value.items():
            path = f"{prefix}.{key}" if prefix else str(key)
            paths.add(path)
            paths.update(_walk(child, path))
    elif isinstance(value, list) and value and isinstance(value[0], dict):
        paths.update(_walk(value[0], f"{prefix}[]"))
    return paths


def _first_real_case(summary: dict[str, Any]) -> dict[str, Any]:
    cases = summary.get("cases")
    if not isinstance(cases, list) or not cases:
        raise ValueError("runtime summary contains no cases")
    case = cases[0]
    if not isinstance(case, dict):
        raise ValueError("first runtime case is not an object")
    return case


def _field_rows(case_paths: set[str]) -> list[dict[str, Any]]:
    # These are the only fields that can be resolved without inventing a new
    # event.  The remaining v2 fields are intentionally marked missing even
    # where an unrelated receipt field looks numerically similar.
    present: dict[str, tuple[bool, str]] = {
        "task_id": (True, "task_id"),
        "delivery_artifact_sha256": (
            True,
            "producer.*.artifact_sha256 and recipient.*.artifact_sha256; digest exists but is not event-bound",
        ),
    }
    rows: list[dict[str, Any]] = []
    for field in fields(Pipe2HandoffDescriptor):
        name = field.name
        available, source = present.get(name, (False, "not present in the native receipt"))
        if name == "schema":
            available = False
            source = f"descriptor schema is defined as {SCHEMA}; receipt does not carry it"
        if name in {"delivery_id", "delivery_path", "delivery_schema"}:
            available = False
            source = "artifact evidence is present, but no typed delivery identity/path/schema field is recorded"
        if name in {"policy_update_allowed", "producer_credit_allowed", "descriptor_digest"}:
            available = False
            source = "generated by the descriptor builder; not recorded by the native receipt"
        rows.append({
            "descriptor_field": name,
            "receipt_mapping": source,
            "available": available,
            "safe_substitution": False if name in {
                "judgment", "action", "used_artifact", "outcome_status",
                "judgment_id", "action_id", "outcome_id", "judgment_record_hash",
                "action_record_hash", "outcome_record_hash", "target_task_index",
            } else None,
        })
    return rows


def run(input_path: Path, output_dir: Path) -> dict[str, Any]:
    input_path = input_path.resolve()
    output_dir = output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=False)
    summary = json.loads(input_path.read_text(encoding="utf-8"))
    case = _first_real_case(summary)
    paths = sorted(_walk(case))
    rows = _field_rows(set(paths))
    config = {
        "runner_version": RUNNER_VERSION,
        "input_summary": str(input_path.relative_to(ROOT)),
        "input_summary_sha256": _sha256(input_path),
        "descriptor_schema": SCHEMA,
        "fixture_mode": "read-only-real-runtime-receipt-field-audit",
        "candidate_code_executed": False,
        "llm_calls": 0,
        "gpu_jobs": 0,
        "native_grader_invoked": False,
        "benchmark_qualified": False,
        "scientific_claim_allowed": False,
        "git_commit": subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True
        ).strip(),
        "python": sys.version,
        "platform": platform.platform(),
        "started_at_utc": _now(),
    }
    (output_dir / "config.json").write_text(
        json.dumps(config, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    raw = {
        "timestamp_utc": _now(),
        "event_type": "pipe2_v2_runtime_field_gap",
        "payload": {"first_case_paths": paths, "field_rows": rows},
    }
    (output_dir / "raw.jsonl").write_text(
        json.dumps(raw, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    missing = [row["descriptor_field"] for row in rows if not row["available"]]
    output = {
        **config,
        "status": "FIELD_GAP_CONFIRMED",
        "case_count_in_source": len(summary.get("cases", [])),
        "first_case_path_count": len(paths),
        "descriptor_field_count": len(rows),
        "available_field_count": sum(row["available"] for row in rows),
        "missing_field_count": len(missing),
        "missing_fields": missing,
        "non_substitutable_fields": [
            "judgment", "action", "used_artifact", "outcome_status",
            "judgment_id", "action_id", "outcome_id", "judgment_record_hash",
            "action_record_hash", "outcome_record_hash", "target_task_index",
        ],
        "interpretation": (
            "The real PIPE2 receipt contains producer and recipient-adoption evidence, "
            "but no bound recipient judgment, consumer action, independent terminal "
            "outcome, later assignment, or pre/post recipient source snapshots. "
            "Adoption, recipient_self, output_sha256, and producer label remain "
            "non-substitutes. The audit does not qualify the benchmark or method."
        ),
        "field_rows": rows,
        "ended_at_utc": _now(),
    }
    (output_dir / "summary.json").write_text(
        json.dumps(output, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    return output


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    result = run(args.input, args.output)
    print(json.dumps({
        key: result[key]
        for key in ("status", "case_count_in_source", "descriptor_field_count",
                    "available_field_count", "missing_field_count")
    }, indent=2))
