num_steps: 200
record_step: 50
repeat_experiment: 2
num_processes: 1
device: cpu
save_models: false
select_partner: true
matgame:
  num_players: 2
  num_actions: 2
  multiplier: 1.0
  scores:
  - - -0.2
    - 0.3
    - -0.3
    - 0.2
  - - -0.2
    - -0.3
    - 0.3
    - 0.2
state:
  len_history: 1
  history_type: single
  agent_id: binary
  include_opponent_history: false
dqn:
  init_params: random
  dims_hidden_layers:
  - 32
  - 16
  epsilon: 0.05
  gamma: 0.99
  freq_refresh_target: 16
  learning_rate: 0.01
  weight_decay: 0.001
population:
  dqn: 4
agentnet:
  name: complete
  netsave_step: 200
  intermediate_plot: false
  frequency_plot: false
  growing: false
  growing_schedule: 0.5
sac_ps:
  init_params: random
  dims_hidden_layers:
  - 32
  - 16
  learning_rate: 0.01
  gamma: 0.99
  alpha: 0.01
  tau: 0.05
  weight_decay: 0.001
  freq_refresh_target: 16
profile_time: false
iteration_modifier: 0
select_partner2: false
freq_rewire: -1
selected_history: false
update_frequency: 1
parallelisation:
  time_sleep: 0.001
print_loss: false
random_seeds:
  experiment: 2329
  agent: 3247
  selector: 8761
  network: 4167
  state: 5397
decay_epsilon: false
profile_qvalues: false
